on:
  push:
    tags:
      # any tag starting with v.x.x.x
      - "v*.*.*"
jobs:
  continuously-deliver:
    # A manual process, if there is an artifact for the commit that
    # has been tagged, then it will publish it, if there's not, error.
    name: Continuous Delivery
    runs-on: "ubuntu-latest"
    environment: pypi
    permissions:
      id-token: write  # required for trusted publishing
    steps:
      - name: "checkout repository so that the package is releasable"
        uses: actions/checkout@v5
      - name: "download wheels directory artifact made in CI"
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: continuous-integration.yaml
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.sha }}
          name: ${{ github.sha }}
          # gh-action-pypi-publish searches for the wheels here
          path: dist/
      - name: "publish package to pypi"
        uses: pypa/gh-action-pypi-publish@release/v1
